name: Deploy Android App to Play Store

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Bump versionCode and versionName
        run: |
          VERSION_CODE=$(grep versionCode app/build.gradle | awk '{ print $2 }')
          VERSION_NAME=$(grep versionName app/build.gradle | awk -F\" '{ print $2 }')
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          NEW_VERSION_NAME=$(echo $VERSION_NAME | awk -F. -v OFS=. '{$NF++;print}')
          sed -i "s/versionCode $VERSION_CODE/versionCode $NEW_VERSION_CODE/" app/build.gradle
          sed -i "s/versionName \"$VERSION_NAME\"/versionName \"$NEW_VERSION_NAME\"/" app/build.gradle

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build App Bundle
        run: ./gradlew bundleRelease

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.gtxtreme.pct
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          whatsNewDirectory: ./whatsnew
        env:
          SUPPRESS_GCLOUD_PROMPT: '1'
